"""Open-source LVS and parasitic extraction support for ASAP7.

The public ASAP7 release does not contain the proprietary Calibre LVS/xACT
rule decks used to create the released standard-cell views.  This package is
therefore a research-grade, explicitly calibrated flow rather than a foundry
sign-off replacement.  See :mod:`chipforge_asap7.verification.pex` for the
assumptions and machine-readable uncertainty report.
"""

from .drc import DRCViolation, drc_counts, find_drc_deck, run_drc
from .lvs import (
    LVSResult,
    find_klayout,
    normalize_asap7_cdl_reference,
    render_bitline_mux_group_lvs_schematic,
    render_bitline_mux_lvs_schematic,
    render_driver_slice_lvs_schematic,
    render_finfet_lvs_schematic,
    render_io_column_lvs_schematic,
    render_nand_lvs_schematic,
    render_nand_row_lvs_schematic,
    render_output_latch_lvs_schematic,
    render_sense_amp_row_lvs_schematic,
    render_write_driver_lvs_schematic,
    run_lvs,
)
from .lvs_report import HierarchicalLVSResult, run_hierarchical_lvs, summarize_lvsdb
from .parasitics import Parasitics, effective_resistance
from .pex import PEXResult, find_fastercap, run_open_pex
from .connectivity import (
    ADJACENT,
    DisjointSetUnion,
    METALS,
    MetalGraph,
    VIAS,
    extract_connectivity,
    filtered_polygon_fingerprint,
    hierarchical_fingerprint,
    layer_polygons,
    overlap,
    polygon_fingerprint,
    process_fingerprint,
    verify_rules,
    verify_tap_rules,
)
from .sram import (
    ACCESS_NFIN,
    CELL_RATIO,
    CONCURRENT_CELL_RATIO,
    CORE_EDGE_CELL_NAMES,
    EDGE_CELL_NAMES,
    ORIENTATIONS,
    PULLDOWN_NFIN,
    PULLUP_NFIN,
    PULLUP_RATIO,
    RECOMMENDED_MIN_CELL_RATIO,
    group_tie_bands,
    is_bitline_m4_rail,
    is_full_m2_rail,
    sizing_report,
    supply_rails,
    tie_bands,
    verify_cap_topology,
    verify_dummy_topology,
    verify_edge_gds,
    verify_gds,
    verify_strap_topology,
    verify_tap_gds,
    verify_tap_topology,
    verify_topology,
    wlb_landing_tracks,
)
from .stack import calibration_manifest, write_kpex_technology

__all__ = [
    "ACCESS_NFIN",
    "ADJACENT",
    "CELL_RATIO",
    "CONCURRENT_CELL_RATIO",
    "CORE_EDGE_CELL_NAMES",
    "DRCViolation",
    "DisjointSetUnion",
    "EDGE_CELL_NAMES",
    "Edit",
    "HierarchicalLVSResult",
    "LVSResult",
    "METALS",
    "MetalGraph",
    "ORIENTATIONS",
    "PEXResult",
    "PULLDOWN_NFIN",
    "PULLUP_NFIN",
    "PULLUP_RATIO",
    "Parasitics",
    "RECOMMENDED_MIN_CELL_RATIO",
    "ReductionConfig",
    "ReductionResult",
    "VIAS",
    "ValidationResult",
    "calibration_manifest",
    "drc_counts",
    "effective_resistance",
    "extract_connectivity",
    "filtered_polygon_fingerprint",
    "find_drc_deck",
    "find_fastercap",
    "find_klayout",
    "group_tie_bands",
    "hierarchical_fingerprint",
    "is_bitline_m4_rail",
    "is_full_m2_rail",
    "layer_polygons",
    "normalize_asap7_cdl_reference",
    "overlap",
    "polygon_fingerprint",
    "process_fingerprint",
    "reduce_layout",
    "render_bitline_mux_group_lvs_schematic",
    "render_bitline_mux_lvs_schematic",
    "render_driver_slice_lvs_schematic",
    "render_finfet_lvs_schematic",
    "render_io_column_lvs_schematic",
    "render_nand_lvs_schematic",
    "render_nand_row_lvs_schematic",
    "render_output_latch_lvs_schematic",
    "render_sense_amp_row_lvs_schematic",
    "render_write_driver_lvs_schematic",
    "run_drc",
    "run_hierarchical_lvs",
    "run_lvs",
    "run_open_pex",
    "sizing_report",
    "summarize_lvsdb",
    "supply_rails",
    "tie_bands",
    "validate_released_inverter",
    "verify_cap_topology",
    "verify_dummy_topology",
    "verify_edge_gds",
    "verify_gds",
    "verify_rules",
    "verify_strap_topology",
    "verify_tap_gds",
    "verify_tap_rules",
    "verify_tap_topology",
    "verify_topology",
    "wlb_landing_tracks",
    "write_kpex_technology",
]
